In [1]:
!pip install gym

In [0]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [0]:
env = gym.make("FrozenLake-v0")

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
num_episodes = 10000
max_steps_per_episode = 10

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [6]:
rewards_all_episodes = []

# Q-Learning algorithm
for episode in range(num_episodes):
  state = env.reset()
  
  done = False
  rewards_current_episode = 0
  
  for step in range(max_steps_per_episode):
    
    # Exploration-exploitation trade-off
    exploration_rate_threshold = random.uniform(0, 1)
    if exploration_rate_threshold > exploration_rate:
      action = np.argmax(q_table[state, :])
    else:
      action = env.action_space.sample()
    
    new_state, reward, done, info = env.step(action)
    
    # Update Q-table for Q(s, a)
    q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
    
    state = new_state
    rewards_current_episode += reward
    
    if done == True:
      break
  
  # Exploration rate decay
  exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
  
  rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("*******Average reward per thousand episodes*******\n")
for r in rewards_per_thousand_episodes:
  print(count, ": ", str(sum(r/1000)))
  count += 1000

# Print updated Q-table
print("\n\n******Q-table*******\n")
print(q_table)

*******Average reward per thousand episodes*******

1000 :  0.009000000000000001
2000 :  0.02100000000000001
3000 :  0.03000000000000002
4000 :  0.04200000000000003
5000 :  0.04300000000000003
6000 :  0.04200000000000003
7000 :  0.03200000000000002
8000 :  0.03900000000000003
9000 :  0.02900000000000002
10000 :  0.047000000000000035


******Q-table*******

[[0.54819869 0.52658981 0.52561264 0.52153406]
 [0.13180373 0.22325198 0.11987018 0.50157072]
 [0.40600734 0.08395523 0.09747722 0.05062905]
 [0.05240459 0.00270941 0.00153995 0.01321986]
 [0.57226651 0.424402   0.43246956 0.30990327]
 [0.         0.         0.         0.        ]
 [0.366791   0.03875761 0.14221625 0.00854171]
 [0.         0.         0.         0.        ]
 [0.42703218 0.44527983 0.38908505 0.58426374]
 [0.39457227 0.62339072 0.29438926 0.29793658]
 [0.57534501 0.32616241 0.42314967 0.27980023]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.22210178 0.24960347 0.7363

In [7]:
for episode in range(3):
  state = env.reset()
  done = False
  print("*******EPISODE ", episode+1, "*******\n\n\n\n")
  time.sleep(1)
  
  for step in range(max_steps_per_episode):
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)
    
    action = np.argmax(q_table[state, :])
    new_state, reward, done, info = env.step(action)
    
    if done:
      clear_output(wait=True)
      env.render()
      if reward == 1:
        print("*******You reached the goal!*******")
        time.sleep(3)
      else:
        print("*******You fell through a hole!******")
        time.sleep(3)
      clear_output(wait=True)
      break
    state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
*******You reached the goal!*******
